server:
  port: ${SERVER_PORT:8181}
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/*]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: service_student
          uri: lb://MS-STUDENT
          predicates:
            - Path=/ms-student/**
          filters:
            - RewritePath=/ms-student/(?<remaining>.*), /$\{remaining}
        - id: service_teacher
          uri: lb://MS-TEACHER
          predicates:
            - Path=/ms-teacher/**
          filters:
            - RewritePath=/ms-teacher/(?<remaining>.*), /$\{remaining}
  #      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

  main:
    web-application-type: reactive
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411}
    enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8763/eureka}
management:
  endpoints:
    web:
      exposure:
        include: "*"